### ISSUE TITLE
Test Versions Differ

### ISSUE THREAD

**Issue by jpshelley** [spekframework/spek#105]
https://kotlinlang.slack.com/archives/spek/p1470260654000104

I tried `1.0.25` but it complains that my kotlin version `1.0.3` differs from my test app (`1.0.2`) so I assume spek isn’t up to date with kotlin?

Will that happen every time Kotlin updates? Seems a bit silly.

**Comment by artem-zinnatullin** [comment]
Just force your build system to use your version of Kotlin in tests. This
is a common problem and not specific to Spek.

**Comment by jpshelley** [comment]
@artem-zinnatullin understandable, I've had it happen plenty of times with other dependencies as well, but since Spek relies on Kotlin (and from the same company) there should be some way of hopefully keeping those in sync so that wouldn't be needed. I have no idea how that would work tho 😅

**Comment by artem-zinnatullin** [comment]
There is no such way, even if Spek will depend on Kotlin 1.0.3 your app may depend on Kotlin 1.0.2 and build will still fail

**Comment by jpshelley** [comment]
Valid point, maybe just need to add documentation to the setup then to point that out. Also if the maintainers had an agreement to keep up to date by the week or something that would be nice.
ie: kotlin 1.0.3 is released, then in 7 days spek will also support it (obviously that might get tricky but would be nice to know)

**Comment by artem-zinnatullin** [comment]
Kotlin 1.x is backward compatible so it shouldn't be a problem for Spek to
work on newer versions of 1.x
