### ISSUE TITLE
gradle not running tests in integration-test directory

### ISSUE THREAD

**Issue by nickgieschen** [spekframework/spek#161]
I have integration tests in src/integration-test/kotlin/foo/bar directory and a custom gradle task to run them. If I have standard junit tests annotated with @test they get run when I run `gradle integrationTest` (which is the name of my custom task). However, this same command doesn't run any spek tests. If I run `gradle test` the spek tests in the standard src/test/kotlin/foo/bar directory do run, as expected. Is there a way I can get the spek tests picked up and run in the integration-test directory?

**Comment by hhariri** [comment]
Do you have them defined in a package or are you using default package?

**Comment by nickgieschen** [comment]
They are defined in a package

**Comment by raniejade** [comment]
Can you paste your build here?

**Comment by nickgieschen** [comment]
apply plugin: "kotlin"
apply plugin: "idea"
apply plugin: "application"
apply plugin: 'org.junit.platform.gradle.plugin'
apply plugin: "org.unbroken-dome.test-sets"

version = "0.1"
mainClassName = "foo.api.App"

repositories {
    mavenCentral()
    maven { setUrl("https://dl.bintray.com/kotlin/exposed") }
    maven { url "http://dl.bintray.com/jetbrains/spek" }
}

buildscript {
    ext.kotlin_version = "1.0.6"
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'org.junit.platform:junit-platform-gradle-plugin:1.0.0-M3'
        classpath 'org.unbroken-dome.gradle-plugins:gradle-testsets-plugin:1.0.2'
    }
}

junitPlatform {
    filters {
        engines {
            include 'spek'
        }
    }
}

testSets {
    integrationTest { dirName = "integration-test" }
}

idea {
    module {
        testSourceDirs += file("src/integration-test/kotlin")
    }
}

dependencies {
    compile "com.sparkjava:spark-core:2.5.2"
    compile "ch.qos.logback:logback-classic:1.0.13"
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    compile "com.github.salomonbrys.kodein:kodein:3.1.0"
    compile "com.github.salomonbrys.kodein:kodein-conf:3.1.0"
    compile "org.postgresql:postgresql:9.4.1212.jre7"
    compile "org.jetbrains.exposed:exposed:0.7.4"
    compile "com.typesafe:config:1.3.1"
    compile "com.github.salomonbrys.kotson:kotson:2.3.0"
    compile "org.apache.httpcomponents:httpclient:4.5.2"
    compile "joda-time:joda-time:2.9.6"
    compile 'io.jsonwebtoken:jjwt:0.7.0'
    compile "org.flywaydb:flyway-core:4.0.3"

    testCompile 'org.assertj:assertj-core:3.6.1'
    testCompile 'org.jetbrains.spek:spek-api:1.1.0-beta3'
    testRuntime 'org.jetbrains.spek:spek-junit-platform-engine:1.1.0-beta3'
    //integrationTestCompile...
}

task wrapper(type: Wrapper) {
    gradleVersion = "3.1"
}

run {
    // Allows us to pass args, e.g. gradle run -Pexec.args="arg1 arg2"
    if (project.hasProperty("exec.args")) {
        args project.getProperty("exec.args").split()
    }
}

**Comment by raniejade** [comment]
Sorry for the delay, I tried doing integration tests for my personal project but I found out that JUnit 5 doesn't support creating your own `test` task. It doesn't integration with gradle's standard `test` task ask well.

**Comment by raniejade** [comment]
Should be possible now, see #572
