### ISSUE TITLE
Add documentation on how to use a different version of kotlin

### ISSUE THREAD

**Issue by raniejade** [spekframework/spek#168]

**Comment by ivanpopelyshev** [comment]
This is real issue, I need it for 1.1, it doesnt work with dependency of kotlin-reflect-1.0.6

**Comment by raniejade** [comment]
@ivanpopelyshev (gradle) this works for me:

```gradle
dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
    compile "org.jetbrains.kotlin:kotlin-reflect:$kotlinVersion"

    compile "org.jetbrains.kotlin:kotlin-test:$kotlinVersion"
    compile ('org.jetbrains.spek:spek-api:1.1.0-beta3') {
        exclude group: 'org.jetbrains.kotlin'
    }

    testCompile 'com.winterbe:expekt:0.5.0'

    testRuntime ('org.jetbrains.spek:spek-junit-platform-engine:1.1.0-beta3') {
        exclude group: 'org.junit.platform'
        exclude group: 'org.jetbrains.kotlin'
    }
}
```

You could also use https://github.com/spring-gradle-plugins/dependency-management-plugin.

**Comment by raniejade** [comment]
Also IDEA plugin is broken when using Kotlin `1.1`, but will release a fix sometime this week.

**Comment by ivanpopelyshev** [comment]
I'm trying to recompile it and publish in my bintray

**Comment by ivanpopelyshev** [comment]
Ok, here it is: "http://dl.bintray.com/hackerham/spek-1.1/"

All except javadocs. Built for 1.1.0-beta-18

**Comment by ivanpopelyshev** [comment]
@raniejade IDEA plugin works for me just fine, with my version of spek. I didn't check it your way.

**Comment by mradzinski** [comment]
@ivanpopelyshev does "http://dl.bintray.com/hackerham/spek-1.1/" has beta38 in it? I saw a ```beta3-b38``` dependency but seems to be empty.

**Comment by ivanpopelyshev** [comment]
fixing it :)

**Comment by ivanpopelyshev** [comment]
Cant configure the version. It just doesnt want to upload jar files :( How to name it?

**Comment by ivanpopelyshev** [comment]
OK, i was stupid, sorry :) I re-created the repo from scratch, use it!

**Comment by mradzinski** [comment]
@ivanpopelyshev You recreated it from scratch at the same location? ```beta3-b38``` is not available anymore :\

**Comment by ivanpopelyshev** [comment]
yep, just purge your cache

**Comment by raniejade** [comment]
@mradzinski @ivanpopelyshev can you test it out, if it works?

```gradle
dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
    compile "org.jetbrains.kotlin:kotlin-reflect:$kotlinVersion"

    compile "org.jetbrains.kotlin:kotlin-test:$kotlinVersion"
    compile ('org.jetbrains.spek:spek-api:1.1.0-beta3') {
        exclude group: 'org.jetbrains.kotlin'
    }

    testCompile 'com.winterbe:expekt:0.5.0'

    testRuntime ('org.jetbrains.spek:spek-junit-platform-engine:1.1.0-beta3') {
        exclude group: 'org.junit.platform'
        exclude group: 'org.jetbrains.kotlin'
    }
}
```

**Comment by mradzinski** [comment]
@raniejade Well, I'm actually writing some tests for Android, so instead of ```testRuntime``` I'm using ```testCompile```. Also, weirdly enough I'm getting a ```Process finished with exit code 255``` error, but I would like to assume is it due to something else (no output, just that message).

**Comment by mradzinski** [comment]
My dependencies look like:

```gradle
dependencies {
    testCompile "org.jetbrains.kotlin:kotlin-test:$kotlin_version"
    testCompile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    testCompile 'com.github.mradzinski:Kluent:v1.5.1'
    testCompile ('org.jetbrains.spek:spek-api:1.1.0-beta3') {
        exclude group: 'org.jetbrains.kotlin'
    }
    testCompile ('org.jetbrains.spek:spek-junit-platform-engine:1.1.0-beta3') {
        exclude group: 'org.junit.platform'
        exclude group: 'org.jetbrains.kotlin'
    }
    testCompile 'org.junit.platform:junit-platform-runner:1.0.0-M3'
}
```

where ```ext.kotlin_version = '1.1.0-beta-38'```

**Comment by raniejade** [comment]
Weird, is the error persistent?

**Comment by mradzinski** [comment]
@raniejade Not anymore, I was running the tests as JUnit tests instead of Spek ones, my bad. Still, now I'm getting something even weirder:

```kotlin
@RunWith(JUnitPlatform::class)
class Test: Spek({
    val array = arrayListOf("Hello", "World")

    given("the array") {
        on("Check object shouldn't be in it") {
            it("should fail") {
                assert(array.contains("Goodbye"))
            }
        }
    }
})
```

Shouldn't that test fail? Because as per the results is passing...

**Comment by raniejade** [comment]
@mradzinski Is runtime assertions enabled? `assert` will not throw an exception if it's disabled.

**Comment by mradzinski** [comment]
@raniejade I think my tests are not getting properly run. If I change the ```should fail``` string to ```should pass``` I keep seeing the original "fail" string on the "Test results" list. Any ideas? I had to manually configure a "Run/Debug Configuration" to use Spek, and on the Gradle tasks list to run before launch I left it as it was by default (only has the "Make" task added).

**Comment by mradzinski** [comment]
@raniejade Never mind, ```assembleDebugUnitTest``` was the proper task. Now everything is working. Thanks for all your help and patience!

**Comment by deviant-studio** [comment]
Error:(305, 18) Failed to resolve: org.jetbrains.spek:spek-junit-platform-engine:1.1.0-beta3
am i doing something wrong?
'beta2' resolved ok

**Comment by raniejade** [comment]
@deviant-studio it's not in central so you have to add the bintray repo.

```gradle
repositories {
    maven { url "http://dl.bintray.com/jetbrains/spek" }
}
```
