### ISSUE TITLE
Expand DSL with 'and' group

### ISSUE THREAD

**Issue by fishb6nes** [spekframework/spek#193]
Heya, I am trying to get used to testing in Kotlin with Spek and Kluent, but coming from Jasmine / Mocha I am finding it difficult to formulate nicely flowing sentences with the DSL available given they actually print out their function names. 

What are your thoughts on making an `and` group available intended for chaining givens?

```
describe("LocalChatChannel") {

	...
	
	given("there is someone nearby") {
	
		beforeGroup() {
			// Stub nearbyUser method to return a player
		}
		
		and("he has the player on mute") {
		
			beforeGroup() {
				// Stub nearby player mock to return true on mute check
			}
		
			on("yelling in the channel") {
				// Invoke action
				
				it("should not send the message to the nearby player") {
					// Assert
				}
			}
		}
	}
}
```

**Comment by raniejade** [comment]
Interesting... I would normally use `context` but `and` feels natural and more readable.

@hhariri @artem-zinnatullin thoughts?

**Comment by hhariri** [comment]
Well for me "given" is the context, so if you want to combine multiple, I think this is more readable.

**Comment by artem-zinnatullin** [comment]
`and` is possibly problematic because it may look like there should also be `or`.

In our practice, we usually do nested `on` blocks with `beforeEach` inside of each and `context` if block does not have `beforeEach`, haven't found a need in adding `and`.

@fishb6nes btw, you can add `and` yourself if you need, just create an extension function: 

```kotlin
fun SpecBody.and(description: String, body: SpecBody.() -> Unit) {
    group("and $description", body = body)
}
```

We do the same to write `perform` instead of `beforeEach` and `cleanup` instead of `afterEach`.

**Comment by raniejade** [comment]
> In our practice, we usually do nested on blocks with beforeEach inside of each and context if block does not have beforeEach, haven't found a need in adding and.

With the latest version you can't nest `on`s anymore.

**Comment by artem-zinnatullin** [comment]
Ah, my bad, well I think my comment is still valid as a general idea.

**Comment by fishb6nes** [comment]
Sweet, thank you for showing how easy it is to add your own groups. I'm conflicted about getting into the habit of using any group I think of on the fly if its not decent enough to make it into the actual Spek though. 

I'd argue against the need or expectation for there to be an `or` group as the tests are constructed in a tree-like fashion. Two sibling groups of the same type represent an `or` situation. If we expand the scenario in the first post with a branch where the nearby player has disabled receiving yell messages:
`given there is someone nearby and he has the player on mute on yelling in the channel it should not send the message to the nearby player`
(implied `or` between the `and` siblings)
`given there is someone nearby and he has disabled yell messages on yelling in the channel it should not send the message to the nearby player`
