### ISSUE TITLE
Spek IntelliJ IDEA plugin doesn't mark `group`, `action`, and `test` blocks as executable.

### ISSUE THREAD

**Issue by mfulton26** [spekframework/spek#199]
The Spek IntelliJ IDEA plugin marks `describe`, `given`, `on`, `it`, etc. as executable but not `group`, `action`, and `test`. They should all be executable, correct?

**Comment by raniejade** [comment]
Nice catch, thanks!

**Comment by raniejade** [comment]
Resolved in `2.x`
