### ISSUE TITLE
Spek doesn't working properly on Android projects

### ISSUE THREAD

**Issue by magnumrocha** [spekframework/spek#207]
Hi guys,

I'm working on a Android Project with the kotlin language. I'm trying to use Spek to test my Presenters classes (yes, I'm using the MVP pattern \o/), but I'm experience some Issues on Spek use.

My tests dependencies are:

```code
// Kotlin library
compile "org.jetbrains.kotlin:kotlin-stdlib-jre7:1.1.2-3"

testCompile "junit:junit:4.12"
testCompile "org.jetbrains.kotlin:kotlin-reflect:1.1.2-3"
testCompile ("com.nhaarman:mockito-kotlin:1.4.0", {
    exclude group: 'org.jetbrains.kotlin'
})
testCompile ("org.jetbrains.spek:spek-api:1.1.1") {
    exclude group: 'org.jetbrains.kotlin'
}
testCompile ("org.jetbrains.spek:spek-junit-platform-engine:1.1.1") {
    exclude group: 'org.junit.platform'
    exclude group: 'org.jetbrains.kotlin'
}
testCompile "org.junit.platform:junit-platform-runner:1.0.0-M4"
```

The problem is that, in my Presenters, I have some calls to the Android Util Log api (eg.: Log.d....), and when I run a Spek I'm get this Exception:

```code
java.lang.RuntimeException: Stub!
	at android.util.Log.d(Log.java:23)
	at com.magnumrocha.sample_kotlin.util.Logger.debug(Logger.kt:31)
	at com.magnumrocha.sample_kotlin.ui.main.MyPresenter.onSearchRequest(MyPresenter.kt:135)
	at com.magnumrocha.sample_kotlin.spek.MyPresenterSpec$1$1$4.invoke(MyPresenterSpec.kt:76)
	at com.magnumrocha.sample_kotlin.spek.MyPresenterSpec$1$1$4.invoke(MyPresenterSpec.kt:28)
	at org.jetbrains.spek.engine.SpekTestEngine$Collector$action$action$1.invoke(SpekTestEngine.kt:175)
	at org.jetbrains.spek.engine.SpekTestEngine$Collector$action$action$1.invoke(SpekTestEngine.kt:133)
	at org.jetbrains.spek.engine.Scope$Action.execute(Scope.kt:55)
	at org.jetbrains.spek.engine.Scope$Action.execute(Scope.kt:38)
	...
```

I think the problem is that Spek is not using the test scope, because my old test using the JUnit framework is working properly.

I have this config on my gradle file:

```code
android {
...
testOptions {
        unitTests.returnDefaultValues = true

        unitTests.all {
            // Display tests results on console
            testLogging {
                events "passed", "skipped", "failed", "standardOut", "standardError"
                outputs.upToDateWhen { false }
                showStandardStreams = true
            }
        }
    }
}
```

The "unitTests.returnDefaultValues = true" make the stuff works on unit tests.

Can you help me with this situation ??

**Comment by raniejade** [comment]
Are you using roboelectric by any chance?

**Comment by magnumrocha** [comment]
Hi @raniejade,

No, I'm not using robolectric. Just the [Mockito-Kotlin](https://github.com/nhaarman/mockito-kotlin) and JUnit asserts.

**Comment by lenguyenthanh** [comment]
Let try to remove `testCompile "junit:junit:4.12"`

**Comment by magnumrocha** [comment]
@lenguyenthanh, I removed and I've got the same Issue.

I think the solution is try make the Spek run using the scope of the JUnit somehow.

**Comment by lenguyenthanh** [comment]
Can you post your test here?

**Comment by magnumrocha** [comment]
Sure:

My Spec code:

```code
/**
 * The specs for [MyPresenter] class.
 *
 * Created by magnumrocha on 05/20/2017.
 */
class MyPresenterSpec: Spek({

    given("a MyPresenter instance") {
        val apiClient: ApiClient = mock()
        val view: MyView = mock()

        // The observer for Data Updates events on Presenter
        val dataUpdatesObserver: TestObserver<DataUpdate> = TestObserver()

        val presenter: MyPresenter = MyPresenter(
            apiClient = apiClient,
            observerScheduler = Schedulers.trampoline(),
            subscriberScheduler = Schedulers.trampoline()
        )

        beforeEachTest {
            // Subscribe the Presenter Data Updates
            presenter.dataUpdatesPublisher.subscribe(dataUpdatesObserver)
        }

        afterEachTest {
            if (!dataUpdatesObserver.isDisposed) {
                dataUpdatesObserver.dispose()
            }
            reset(apiClient)
            reset(view)
        }

        on("on view attached") {
            presenter.onViewAttached(view)

            it("should not emit some error on Data Updates Subject") {
                dataUpdatesObserver.assertNoErrors()
            }

            it("should not complete the Data Updates Subject") {
                dataUpdatesObserver.assertNotComplete()
            }

            it("should emit the \"NoData\" object on Data Updates Subject") {
                // -> Check the last item emitted
                val lastUpdate = dataUpdatesObserver.values().last()
                Assert.assertTrue(lastUpdate is NoData)
            }
        }

    }

})
```

My Presenter code:

```code
/**
 * The MyPresenter class.
 *
 * Created by magnumrocha on 05/20/2017.
 */
class MyPresenter(
        private val apiClient: ApiClient,
        private val subscriberScheduler : Scheduler,
        private val observerScheduler: Scheduler
): Presenter<MyView> {

    private var view : MyView? = null

    private var currentData: MyData? = null

    /**
     * Subject to publish the Data updates.
     */
    var dataUpdatesPublisher: BehaviorSubject<DataUpdate> = BehaviorSubject.create()
        private set

    override fun onViewAttached(view: MyView) {
        this.view = view

        if (currentData == null) {
            Log.d("MyPresenter", "Publishing NoData requested !!!")
            dataUpdatesPublisher.onNext(NoData())
        }
    }

    override fun onViewDetached() {
        this.view = null
    }

...

}
```

**Comment by lenguyenthanh** [comment]
Let try:
```
@RunWith(JUnitPlatform::class)
class MyPresenterSpec: Spek({```

**Comment by magnumrocha** [comment]
Same Issue 😢 

When we apply the @RunWith(JUnitPlatform::class), it causes some confusion to the Spek plugin, it won’t recognize our spec and create a JUnit config to run your spec instead — which doesn’t work (in Android Studio 2.3, Spek plugin 0.3.3)

**Comment by lenguyenthanh** [comment]
It seems Spek plugin doesn't work with Android Studio because it AndroidJunit uses JUnit 4. My app works well with Spek 1.1.1 and Android studio 2.3.

**Comment by raniejade** [comment]
If you're using `@Runwith(JUnitPlatform::class)` the spek plugin won't work as the JUnit plugin will take over.

Is it possible to stub out logging that doesn't use androids logging features? Spek doesn't support android instrumentation tests. It will run the tests in the JVM, the android runtime will not be initialized.

**Comment by magnumrocha** [comment]
I'm using Spek for my local unit tests, I already known that Spek doesn't work with Android Instrumentation Tests.

We can wrap the Android Log Util class, and check the presence of Spek class on runtime, using Class.forName("org.jetbrains.spek.api.Spek"), but I don't consider this a good solution, because for any android.jar class that I use on my Presenter, I will need do this check.

I was using the Spek Idea Plugin, and it is working very nice, but the problem is the use of android.jar classes and member on parts of the code that will be tested.

As I mentioned before, the "unitTests.returnDefaultValues = true" make the stuff works on unit tests:

```code
android {
...
testOptions {
        unitTests.returnDefaultValues = true
    }
}
```

**Comment by raniejade** [comment]
Okay so you want Spek to work without `unitTests.returnDefaultValues = true`? Or does it now work with Spek? Sorry, I'm still trying to understand the problem here.

**Comment by magnumrocha** [comment]
@raniejade, sorry for my bad english 😄 .

The problem is Spek is not working as JUnit works with android.jar class and members.

Right now, I don't know if the problem is on Spek or Spek Idea Plugin, that is not considering the `unitTests.returnDefaultValues = true` config like JUnit does.

**Comment by raniejade** [comment]
No worries. Android support is not that great right now, we are currently looking for ways to improve this. 
Spek does not know about `unitTests.returnDefaultValues = true`, it's very specific to the android tooling.

If you want to stick with `unitTests.returnDefaultValues = true`, you have to use `@RunWith(JUnitPlatform::class)` - this means that you will lose IDE support (junit plugin will takeover).

If you want to use the spek plugin, you need to make sure that no android API is being called when running the tests. In your case, you could take a look at SLF4J (https://github.com/qos-ch/slf4j).

**Comment by magnumrocha** [comment]
I can't run my Spek tests with `@Runwith(JUnitPlatform::class)`, the tests don't run.

I put the gradle task "app:assembleDebugUnitTest" on Before launch of Run Configuration, but this not worked.

**Comment by raniejade** [comment]
You can't use spek run configuration, the bundled junit plugin should take over. Just delete any spek run configuration you have and create a new "JUnit" run configuration instead.

**Comment by radityagumay** [comment]
@magnumrocha are you solve that issue? i also face same problem
