### ISSUE TITLE
Programmatically ignore/skip test

### ISSUE THREAD

**Issue by mattbdean** [spekframework/spek#219]
Is there currently a way to ignore/skip tests programmatically? I saw #5, but I'm not sure if anything came out of it.

In TestNG we can simply throw a `SkipException` to skip a test. For JUnit 4, this [StackOverflow post](https://stackoverflow.com/a/1689309) seems to say that if an assumption failed, the test would be skipped. Maybe I'm doing something wrong, but this doesn't seem to be the case with Spek (or maybe in JUnit 5 as a whole)

```kotlin
class SampleSpek : Spek({
    describe("foo") {
        it("should be skipped") {
            assumeTrue(false)
        }
    }
})
```

```
org.junit.AssumptionViolatedException: got: <false>, expected: is <true>
```

**Comment by raniejade** [comment]
@thatJavaNerd  each scope (given, describe, on, it, etc..) has a version prefixed w/ an `x`, spek will skip them.

```kotlin
class SampleSpek : Spek({
    describe("foo") {
        xit("should be skipped") {
            assumeTrue(false)
        }
    }
})
```

**Comment by thatJavaNerd** [comment]
Is there a way we can skip these scopes programmatically?

**Comment by artem-zinnatullin** [comment]
Yes there is a way to have conditional Spek branches:

```kotlin
MySpec : Spek({
    context("something happens") {

        fun SpecBody.itChecksSomethingSometimes(check: Boolean) {
            // You can access local variables, etc.
            if (check) {
                it("is something") {
                    assertThat(something).isEqualTo(expectedThing)
                }
            }
        }

        it("makes the world a better place") {
            assertThat(world).isABetterPlaceNow()
        }

        itChecksSomethingSometimes(checkOrNot)
    }
})
```

With such extension functions with receiver you can create conditional Spek branches programmatically.

**Comment by thatJavaNerd** [comment]
I didn't know that! Is there a way we can skip tests while we're inside an `it` body? Something like

```kotlin
it("should be skipped") {
    skip()
    assertTrue(false)
}
```

**Comment by artem-zinnatullin** [comment]
Not really, probably just skip the body of the test, however you'll still
see it in the report as passed.

I think you better go with dynamic spec branch generation as I showed
above, you can even produce xit() branch to clearly see that it was
ignored.

**Comment by raniejade** [comment]
You could also use `test`:

```kotlin
fun someCondition(condition: Boolean, reason: String = "no reason") = if (condition) Pending.No else Pending.Yes(reason)

class MySpec: Spek({
    test("do something", pending = someCondition(<something>)) {
        ...
    }
})

**Comment by thatJavaNerd** [comment]
Thank you!

I ended up using something similar to what @artem-zinnatullin suggested:

```kotlin
fun SpecBody.assume(check: () -> Boolean, description: String, body: TestBody.() -> Unit) {
    if (check())
        it(description, body)
    else
        xit(description, reason = "assumption failed", body = body)
}
```

Are there any plans to include something like this in the API?
