### ISSUE TITLE
IntelliJ IDEA: "Test events were not received"

### ISSUE THREAD

**Issue by tyrondis** [spekframework/spek#235]
I set up `Spek` with `Gradle` according to the documentation provided here:
http://spekframework.org/docs/latest/#_gradle

Upon running `gradle test` as a Gradle task from within IntelliJ IDEA, the tests run successfully and I can see the test summary in the test output console, however, the tree that normally lists each tests with a visual indicator just shows the text "Test events were not received".

How can I configure Spek so that IDEA is able to pick up the test results?

IntelliJ IDEA: 2017.2.1
Spek: 1.1.2
Gradle: 4.0.2

**Comment by raniejade** [comment]
It's not working as of the moment, I think it only works for JUnit 4 tests.
