### ISSUE TITLE
Inconsistency in docs of "describe, it" style

### ISSUE THREAD

**Issue by sgrimm-sg** [spekframework/spek#252]
The documentation of the "describe, it" style says that this style involves `describe` and `it` blocks, the former of which can be nested. But the example code has `describe`, `on`, and `it`. The `on` blocks should probably be `describe` instead to demonstrate nesting.

**Comment by Rosomack** [comment]
Nesting is also supported by the `given - on - it` convention. `given` blocks can be nested, and I think the documentation should reflect that too.
