### ISSUE TITLE
Provide Gradle plugin for JVM-based projects

### ISSUE THREAD

**Issue by raniejade** [spekframework/spek#267]
The idea here is to provide a faster way to setup spek and hide complications of setting up JUnit Platform.

```gradle
plugins {
    id 'org.spekframework.jvm' 
}
```

Multiple Source Sets
---------------------------
The plugin should support multiple source sets but also provide a sensible default.

```gradle
spek {
   test {
        // default mapped to src/test/kotlin
   }

   custom {
        // mapped to src/custom/kotlin
   }
}
```

Managed Spek dependencies
----------------------------------------
No need to manually specify a dependency to spek, just apply the plugin and you're good to go. You can specify version per source set.

```gradle
spek {
   version = '2.1.0'
   test {
        // override
        version = '2.0.0'
   }

   custom {
        // version inherited '2.1.0'
   }
}
```

**Comment by robstoll** [comment]
You might want to have a look at: https://github.com/robstoll/tutteli-gradle-plugins/blob/master/tutteli-gradle-spek/src/main/groovy/ch/tutteli/gradle/spek/SpekPlugin.groovy

it does not fulfil all the requirements stated above but might be a good starting place; especially if you want to provide support for gradle < 4.6 => feel free to copy.
If your plugin targets Gradle >= 4.6, then it should be done differently (gradle 4.6 introduce junit5 support)
