### ISSUE TITLE
Improve grouping in JUnit test reports

### ISSUE THREAD

**Issue by madhead** [spekframework/spek#52]
I've setup a test repo for this issue [here](https://github.com/madhead/spek-reports).

When I run Spek suites in IntelliJ IDEA, the reports looks awesome:
![IntelliJ IDEA test report](https://cloud.githubusercontent.com/assets/577360/15592412/35729cb8-23ac-11e6-9a49-87295f04791e.png)

Suite class's name is visible alongside with it's package. The sings are aligned in tree. Just great.

But when I run tests in Gradle (`./gradlew test`) the report (`build/reports/tests/index.html`) is not so good:
![Gradle test report - root](https://cloud.githubusercontent.com/assets/577360/15592483/e22286b2-23ac-11e6-8071-6eca9eb42df0.png)
![Gradle test report - default-package expanded](https://cloud.githubusercontent.com/assets/577360/15592486/e7bcf274-23ac-11e6-868d-993976bc1016.png)
![Gradle test report - arithmetics expanded](https://cloud.githubusercontent.com/assets/577360/15592492/eb4ddebc-23ac-11e6-9343-0decdd37eea6.png)
- Everything is put inside `default-package`, which is not true.
- `given` / `describe` / `on` blocks appear in one list.

I understand that reports are not supposed to support custom tree structures, but wouldn't it be better if `describe` goes to package name and all `on`s being grouped by them?

Also, XML reports should be tweaked too to improve reporting on CI...

**Comment by upelsin** [comment]
Any plans for this?

**Comment by georgepapas** [comment]
bump...
+1

**Comment by raniejade** [comment]
We just upgraded to JUnit 5 which should fix the XML reports. However currently it doesn't generate the html reports.  We will be releasing 1.0 soon, so stay tuned.

**Comment by upelsin** [comment]
As of Spek 1.0.89, tests still reside in `default-package`.

**Comment by ubuntudroid** [comment]
As we're stuck with Junit4 on Android I'd like to know whether you're planning on improving grouping there as well.

**Comment by artem-zinnatullin** [comment]
@ubuntudroid we're not stuck with JUnit4 "on Android", if you run tests on JVM, you can use JUnit5 (with few hacks for now, but still possible)!

**Comment by ubuntudroid** [comment]
@artem-zinnatullin AFAIK there is no official JUnit 4 support in the Android Gradle Plugin.

But if it's possible without breaking Android Studio's unit testing capabilities this would be a great thing. Spek's own documentation just mentions Junit4 support for Android. Would you mind updating it? https://github.com/JetBrains/spek/blob/master/documentation/src/asciidoc/setting-up.adoc#setting-up-legacy

**Comment by kiyoshi-shikuma** [comment]
bump +1

**Comment by grine4ka** [comment]
Do I understand correctly that this issue is blocked by some issues in gradle?
Like these:
[#4438](https://github.com/gradle/gradle/issues/4438)
[#4252](https://github.com/gradle/gradle/issues/4252)

**Comment by jcornaz** [comment]
Will this issue be solved for Spek `2.0.0`?

Loosing hierarchy information in reports make it very cumbersome to track the cause of failing tests.

@grine4ka I don't see how it could be related. Theses are *gradle* issue. Spek shall produce good test reports independently on the build system used. No matter if it is gradle, maven or something else.

**Comment by raniejade** [comment]
@grine4ka is correct as we depend on gradle for generating reports. Spek already reports the proper hierarchy , it's all up to gradle on how it is rendered.

**Comment by jcornaz** [comment]
Thanks @raniejade for the precision. Does it mean that maven users don't experience this issue?

**Comment by raniejade** [comment]
I'm not sure, I don't use maven that much.

**Comment by jcornaz** [comment]
> I'm not sure, I don't use maven that much.

I experienced the same with Maven.

> Spek already reports the proper hierarchy , it's all up to gradle on how it is rendered.

Should this issue be closed then?

Or maybe Spek could provide a workaround? By concatenating the hierarchy information in the test name for instance.

**Comment by raniejade** [comment]
> Or maybe Spek could provide a workaround? By concatenating the hierarchy information in the test name for instance.

Nope, hacky solutions will only add more problems.
