### ISSUE TITLE
spek tree result in IntelliJ IDEA - only shows text after last period (.)

### ISSUE THREAD

**Issue by mfulton26** [spekframework/spek#98]
This is probably a JUnit/IDEA reporter thing but if a `describe`/`on`/`it`/etc. block description contains a period (.) then IntelliJ DEA only displays the portion of the description string after the last period. e.g. "a calculator with a current display value of 4.11" is displayed as simply "11".

**Comment by artem-zinnatullin** [comment]
Yeah, even more weird stuff happens if you try to put brackets in names

**Comment by raniejade** [comment]
Yeah, there are certain characters that are used internally to represent hierarchy (e.g `foo (bar)` - `foo` will be treated as a method of `bar`). `.` is also special. We are moving to JUnit 5 and hopefully this gets fixed.
